Create Table Regions (
	Id int NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(255),
	ShortCode NVARCHAR(5),
	CountryId int,
	CountryName NVARCHAR(255),
	FOREIGN KEY (CountryId) REFERENCES Countries(Id)
)


INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Badakhshan','BDS',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Badghis','BDG',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Baghlan','BGL',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Balkh','BAL',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Bamyan','BAM',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Daykundi','DAY',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Farah','FRA',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Faryab','FYB',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Ghazni','GHA',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Ghor','GHO',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Helmand','HEL',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Herat','HER',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Jowzjan','JOW',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Kabul','KAB',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Kandahar','KAN',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Kapisa','KAP',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Khost','KHO',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Kunar','KNR',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Kunduz','KDZ',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Laghman','LAG',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Logar','LOW',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Maidan Wardak','WAR',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Nangarhar','NAN',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Nimruz','NIM',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Nuristan','NUR',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Paktia','PIA',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Paktika','PKA',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Panjshir','PAN',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Parwan','PAR',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Samangan','SAM',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Sar-e Pol','SAR',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Takhar','TAK',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Urozgan','ORU',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Afghanistan','Zabul','ZAB',1)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Albania','Berat','1',2)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Albania','Dibër','9',2)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Albania','Durrës','2',2)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Albania','Elbasan','3',2)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Albania','Fier','4',2)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Albania','Gjirokastër','5',2)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Albania','Korçë','6',2)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Albania','Kukës','7',2)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Albania','Lezhë','8',2)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Albania','Shkodër','10',2)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Albania','Tirana','11',2)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Albania','Vlorë','12',2)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('American Samoa','Tutuila','1',4)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('American Samoa','Aunu''u','2',4)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('American Samoa','Ta''ū','3',4)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('American Samoa','Ofu‑Olosega','4',4)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('American Samoa','Rose Atoll','21',4)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('American Samoa','Swains Island','22',4)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Argentina','Buenos Aires','B',9)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Argentina','Capital Federal','C',9)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Argentina','Catamarca','K',9)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Argentina','Chaco','H',9)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Argentina','Chubut','U',9)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Argentina','Córdoba','X',9)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Australia','Australian Capital Territory','ACT',12)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Australia','New South Wales','NSW',12)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Australia','Northern Territory','NT',12)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Australia','Queensland','QLD',12)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Australia','South Australia','SA',12)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Australia','Tasmania','TAS',12)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Australia','Victoria','VIC',12)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Australia','Western Australia','WA',12)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Canada','Alberta','AB',35)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Canada','British Columbia','BC',35)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Canada','Manitoba','MB',35)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Canada','New Brunswick','NB',35)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Canada','Newfoundland and Labrador','NL',35)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Canada','Northwest Territories','NT',35)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Canada','Nova Scotia','NS',35)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Canada','Nunavut','NU',35)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Canada','Ontario','ON',35)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Canada','Prince Edward Island','PE',35)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Canada','Quebec','QC',35)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Canada','Saskatchewan','SK',35)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Canada','Yukon','YT',35)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Italy','Abruzzo','65',89)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Italy','Basilicata','77',89)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Italy','Calabria','78',89)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Italy','Campania','72',89)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Italy','Emilia-Romagna','45',89)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Italy','Friuli-Venezia Giulia','36',89)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Italy','Lazio','62',89)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Italy','Liguria','42',89)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Italy','Lombardia','25',89)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Italy','Marche','57',89)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Italy','Molise','67',89)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Italy','Piemonte','21',89)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Italy','Puglia','75',89)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Italy','Sardegna','88',89)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Italy','Sicilia','82',89)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Italy','Toscana','52',89)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Italy','Trentino-Alto Adige','32',89)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Italy','Umbria','55',89)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Italy','Valle d''Aosta','23',89)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Italy','Veneto','34',89)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Singapore','Central Singapore','1',166)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Singapore','North East','2',166)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Singapore','North West','3',166)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Singapore','South East','4',166)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('Singapore','South West','5',166)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('United Kingdom','Aberdeen City','ABE',199)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('United Kingdom','Aberdeenshire','ABD',199)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('United Kingdom','Angus','ANS',199)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('United Kingdom','Antrim and Newtownabbey','ANN',199)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('United Kingdom','Ards and North Down','AND',199)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('United Kingdom','Argyll and Bute','AGB',199)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('United Kingdom','Armagh City, Banbridge and Craigavon','ABC',199)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('United Kingdom','Barking and Dagenham','BDG',199)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('United Kingdom','Barnet','BNE',199)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('United Kingdom','Barnsley','BNS',199)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('United Kingdom','Bath and North East Somerset','BAS',199)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('United Kingdom','Bedford','BDF',199)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('United Kingdom','Belfast City','BFS',199)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('United Kingdom','Berkshire','BRK',199)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('United Kingdom','Bexley','BEX',199)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('United Kingdom','Birmingham','BIR',199)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('United Kingdom','Blackburn with Darwen','BBD',199)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('United Kingdom','Blackpool','BPL',199)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('United Kingdom','Blaenau Gwent','BGW',199)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('United Kingdom','Bolton','BOL',199)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('United Kingdom','Bournemouth, Christchurch and Poole','BCP',199)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('United Kingdom','Bracknell Forest','BRC',199)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('United Kingdom','Bradford','BRD',199)
INSERT INTO Regions (CountryName, Name, ShortCode, CountryId) Values('United Kingdom','Brent','BEN',199)

Alter TABLE Regions DROP COLUMN CountryName

SELECT * FROM Regions